[package]
name = "request-channel"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/request-channel"

[lib]
name = "request_channel"
path = "lib.rs"

[dependencies]
tokio = { version = "1", features = ["sync", "time"] }
